language: python

python:
    - 2.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz
    - sudo apt-get install -y imagemagick
    - sudo apt-get install -y texlive 
    - sudo apt-get install -y texlive-fonts-recommended
    - sudo apt-get install -y texlive-latex-extra 
    - sudo apt-get install -y texlive-latex-recommended 
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.15-1.linux-64.sh
    - sudo sh lilypond-2.19.15-1.linux-64.sh --batch
    - pip install coveralls
    - pip install coverage

install:
    - pip install -r requirements.txt
    - pip install -e . 

before_script:
    - export PYTHONPATH=$TRAVIS_BUILD_DIR/ide/scores:${PYTHONPATH}
    - echo $PYTHONPATH

script:
    - start-abjad-ide cw q
    - coverage run -a `which ajv` doctest ide
    - coverage run -a `which py.test` -rf ide
    - ajv api -RI

after_success:
    coveralls