language: python

python:
    - 2.7
    - 3.4

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz
    - sudo apt-get install -y imagemagick
    - sudo apt-get install -y texlive 
    - sudo apt-get install -y texlive-fonts-recommended
    - sudo apt-get install -y texlive-latex-extra 
    - sudo apt-get install -y texlive-latex-recommended 
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.29-1.linux-64.sh
    - sudo sh lilypond-2.19.29-1.linux-64.sh --batch
    - pip install --upgrade pip
    - pip install coveralls
    - pip install coverage

install:
    - pip install -r requirements.txt
    - pip install -e . 

before_script:
    - ide/scr/prime-parser-tables

script:
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/blue_example_score:$PYTHONPATH
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/red_example_score:$PYTHONPATH
    - echo $PYTHONPATH
    # Travis can not find the ide/scr directory
    #- start-abjad-ide q
    - coverage run -a `which ajv` doctest ide
    - coverage run -a `which py.test` -rf ide
    - ajv api -RI

after_success:
    coveralls