language: python

sudo: false

python:
    - 3.6

addons:
    apt:
        packages:
            - graphviz
            - imagemagick
            - pgf
            - texlive
            - texlive-extra-utils
            - texlive-fonts-recommended
            - texlive-latex-extra
            - texlive-latex-recommended
            - texlive-xetex

before_install:
    - LILYPOND_SCRIPT=lilypond-2.19.80-1.linux-64.sh
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_URL=$LILYPOND_URL/$LILYPOND_SCRIPT
    - wget -q $LILYPOND_URL
    - sh $LILYPOND_SCRIPT --batch
    - git clone https://github.com/Abjad/abjad.git;
    - cd abjad; git checkout trevor/dev; pip install -e .[development]
    - echo `git branch`
    - cd ..
    - pip install --upgrade pip
    - pip install coverage
    - which latex
    - which xetex
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/blue_score:$PYTHONPATH
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/red_score:$PYTHONPATH
    - echo $PYTHONPATH
    - pwd
    - ls
    - echo $PATH
    - PATH=$PATH:`pwd`:`pwd`/ide/scr
    - echo $PATH
    - MYPYPATH=$PYTHONPATH:`pwd`
    - export MYPYPATH
    - echo $MYPYPATH

install:
    - pip install -e git://github.com/trevorbaca/baca.git#egg=baca
    - pip install -r requirements.txt
    - pip install -e . 

before_script:
    - ide/scr/prime-parser-tables
    - echo `which start-abjad-ide`

script:
    - start-abjad-ide q
    - mypy ide
    - coverage run -a `which ajv` doctest ide
    - coverage run -a `which py.test` -rf ide
    - ajv api -IR

after_success:
    - pip install coveralls
    - coveralls
