language: python

sudo: false

python:
    - 3.6

addons:
    apt:
        packages:
        - graphviz
        - imagemagick
        - pgf
        - texlive
        - texlive-extra-utils
        - texlive-fonts-recommended
        - texlive-latex-extra
        - texlive-latex-recommended
        - texlive-xetex

before_install:
    # alias package
    - PACKAGE=`pwd`/ide
    - export PATH=$PATH:$PACKAGE/scr

    # install lilypond:
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_SCRIPT=lilypond-2.19.80-1.linux-64.sh
    - wget -q -O /tmp/$LILYPOND_SCRIPT $LILYPOND_URL/$LILYPOND_SCRIPT
    - sh /tmp/$LILYPOND_SCRIPT --batch

    # upgrade pip:
    - pip install --upgrade pip

    # clone & install abjad dev branch:
    - ABJAD=/tmp/abjad
    - git clone -b trevor/dev https://github.com/Abjad/abjad.git $ABJAD
    - pip install -e $ABJAD
    - export MYPYPATH=$ABJAD

    # clone & install rmakers:
    - RMAKERS=/tmp/abjad-ext-rmakers
    - git clone https://github.com/Abjad/abjad-ext-rmakers.git $RMAKERS
    - pip install -e $RMAKERS
    - export MYPYPATH=$MYPYPATH:$RMAKERS

    # clone & install baca:
    - BACA=/tmp/baca
    - git clone https://github.com/trevorbaca/baca.git $BACA
    - pip install -e $BACA
    - export MYPYPATH=$MYPYPATH:$BACA
    - export PATH=$PATH:$BACA/baca/scr

    # install uqbar:
    - UQBAR=/tmp/uqbar
    - pip install --no-deps --target $UQBAR uqbar
    - export MYPYPATH=$MYPYPATH:$UQBAR

    # set pythonpath; is this needed anymore?
    - export PYTHONPATH=$PYTHONPATH:$PACKAGE/scores/blue_score
    - export PYTHONPATH=$PYTHONPATH:$PACKAGE/scores/red_score
    - export PYTHONPATH=$PYTHONPATH:$PACKAGE/scores/green_score

    # log setup:
    - echo $MYPYPATH
    - echo $PATH
    - echo $PYTHONPATH
    - ls
    - ls /tmp
    - pwd
    - which doctest
    - which latex
    - which prime-parser-tables
    - which start-abjad-ide
    - which xetex

install:
    - pip install coverage
    - pip install -e . 
    - prime-parser-tables

script:
    - mypy $PACKAGE
    - start-abjad-ide q
    - coverage run -a `which doctest` $PACKAGE/*.py
    - coverage run -a `which py.test` -rf $PACKAGE

after_success:
    - pip install coveralls
    - coveralls
