language: python

sudo: false

python:
    - 3.6

addons:
    apt:
        packages:
            - graphviz
            - imagemagick
            - pgf
            - texlive
            - texlive-extra-utils
            - texlive-fonts-recommended
            - texlive-latex-extra
            - texlive-latex-recommended
            - texlive-xetex

before_install:
    - LILYPOND_SCRIPT=lilypond-2.19.65-1.linux-64.sh
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_URL=$LILYPOND_URL/$LILYPOND_SCRIPT
    - wget -q $LILYPOND_URL
    - sh $LILYPOND_SCRIPT --batch
    - git clone https://github.com/Abjad/abjad.git;
    - cd abjad; git checkout trevor/dev; pip install -e .[development]
    - echo `git branch`
    - cd ..
    - pip install --upgrade pip
    - pip install coveralls
    - pip install coverage
    - which latex
    - which xetex

install:
    - pip install -r requirements.txt
    - pip install -e . 

before_script:
    - ide/scr/prime-parser-tables

script:
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/blue_score:$PYTHONPATH
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/red_score:$PYTHONPATH
    - echo $PYTHONPATH
    # Travis can not find the ide/scr directory
    #- start-abjad-ide q
    - coverage run -a `which ajv` doctest ide
    - coverage run -a `which py.test` -rf ide
    - ajv api -RI

after_success:
    coveralls
