language: python

sudo: false

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

addons:
    apt:
        packages:
            - graphviz
            - imagemagick
            - texlive
            - texlive-extra-utils
            - texlive-fonts-recommended
            - texlive-latex-extra
            - texlive-latex-recommended

before_install:
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.38-1.linux-64.sh
    - sh lilypond-2.19.38-1.linux-64.sh --batch
    - pip install --upgrade pip
    - pip install coveralls
    - pip install coverage

install:
    - pip install -r requirements.txt
    - pip install -e . 

before_script:
    - ide/scr/prime-parser-tables

script:
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/blue_example_score:$PYTHONPATH
    - export PYTHONPATH=/home/travis/build/Abjad/ide/ide/scores/red_example_score:$PYTHONPATH
    - echo $PYTHONPATH
    # Travis can not find the ide/scr directory
    #- start-abjad-ide q
    - coverage run -a `which ajv` doctest ide
    - coverage run -a `which py.test` -rf ide
    - ajv api -RI

after_success:
    coveralls